namespace SharpIDE.SourceGenerators.InputMapName;

public class InputMapNameConstants
{
	public const string PropertiesPlaceholder = "{Properties}";
	public const string Code = $$"""
	                           // <auto-generated/>
	                           using Godot;
	                           namespace SharpIDE.Godot;

	                           public static partial class InputStringNames
	                           {
	                           {{PropertiesPlaceholder}}
	                           }
	                           """;
}
