using Godot;

namespace SharpIDE.Godot.Features.Common;

public static partial class ThemeGenerator
{
    private static Theme CreateDarkTheme()
    {
        var theme = new Theme();
        theme.DefaultFont = ResourceLoader.Load<Font>("uid://38igu11xwba6");
        theme.SetTypeVariation("CodeEditorTabContainer", "TabContainer");
        theme.SetTypeVariation("EditorHoverPopupPanelContainer", "PanelContainer");
        theme.SetTypeVariation("Gray500Label", "Label");
        theme.SetTypeVariation("Gray600Label", "Label");
        theme.SetTypeVariation("Gray700Label", "Label");
        theme.SetTypeVariation("Gray800Label", "Label");
        theme.SetTypeVariation("IdeSidebarButton", "Button");
        theme.SetTypeVariation("NavigationArrowButton", "Button");

        var styleBox0 = new StyleBoxFlat();
        styleBox0.ResourceSceneUniqueId = "StyleBoxFlat_dwjdr";
        styleBox0.Set("content_margin_left", 4.0);
        styleBox0.Set("content_margin_top", 4.0);
        styleBox0.Set("content_margin_right", 4.0);
        styleBox0.Set("content_margin_bottom", 4.0);
        styleBox0.Set("bg_color", new Color(1f, 1f, 1f, 0.0627451f));
        styleBox0.Set("border_width_left", 1);
        styleBox0.Set("border_width_top", 1);
        styleBox0.Set("border_width_right", 1);
        styleBox0.Set("border_width_bottom", 1);
        styleBox0.Set("border_color", new Color(1f, 1f, 1f, 0.1254902f));
        styleBox0.Set("border_blend", true);
        styleBox0.Set("corner_radius_top_left", 3);
        styleBox0.Set("corner_radius_top_right", 3);
        styleBox0.Set("corner_radius_bottom_right", 3);
        styleBox0.Set("corner_radius_bottom_left", 3);
        styleBox0.Set("corner_detail", 5);
        theme.SetStylebox("hover", "Button", styleBox0);

        var styleBox1 = new StyleBoxFlat();
        styleBox1.ResourceSceneUniqueId = "StyleBoxFlat_kyxro";
        styleBox1.Set("content_margin_left", 4.0);
        styleBox1.Set("content_margin_top", 4.0);
        styleBox1.Set("content_margin_right", 4.0);
        styleBox1.Set("content_margin_bottom", 4.0);
        styleBox1.Set("bg_color", new Color(1f, 1f, 1f, 0.030000001f));
        styleBox1.Set("border_width_left", 1);
        styleBox1.Set("border_width_top", 1);
        styleBox1.Set("border_width_right", 1);
        styleBox1.Set("border_width_bottom", 1);
        styleBox1.Set("border_color", new Color(1f, 1f, 1f, 0.101960786f));
        styleBox1.Set("border_blend", true);
        styleBox1.Set("corner_radius_top_left", 3);
        styleBox1.Set("corner_radius_top_right", 3);
        styleBox1.Set("corner_radius_bottom_right", 3);
        styleBox1.Set("corner_radius_bottom_left", 3);
        styleBox1.Set("corner_detail", 5);
        theme.SetStylebox("normal", "Button", styleBox1);

        var styleBox2 = new StyleBoxFlat();
        styleBox2.ResourceSceneUniqueId = "StyleBoxFlat_5v2og";
        styleBox2.Set("content_margin_left", 4.0);
        styleBox2.Set("content_margin_top", 4.0);
        styleBox2.Set("content_margin_right", 4.0);
        styleBox2.Set("content_margin_bottom", 4.0);
        styleBox2.Set("bg_color", new Color(0f, 0f, 0f, 0.19607843f));
        styleBox2.Set("border_width_left", 1);
        styleBox2.Set("border_width_top", 1);
        styleBox2.Set("border_width_right", 1);
        styleBox2.Set("border_width_bottom", 1);
        styleBox2.Set("border_color", new Color(1f, 1f, 1f, 0.0627451f));
        styleBox2.Set("border_blend", true);
        styleBox2.Set("corner_radius_top_left", 3);
        styleBox2.Set("corner_radius_top_right", 3);
        styleBox2.Set("corner_radius_bottom_right", 3);
        styleBox2.Set("corner_radius_bottom_left", 3);
        styleBox2.Set("corner_detail", 5);
        theme.SetStylebox("pressed", "Button", styleBox2);

        var styleBox3 = new StyleBoxFlat();
        styleBox3.ResourceSceneUniqueId = "StyleBoxFlat_38n5o";
        styleBox3.Set("bg_color", new Color(0.16862746f, 0.1764706f, 0.1882353f, 1f));
        styleBox3.Set("border_width_left", 1);
        styleBox3.Set("border_width_top", 1);
        styleBox3.Set("border_width_right", 1);
        styleBox3.Set("border_width_bottom", 1);
        styleBox3.Set("border_color", new Color(0.24313726f, 0.2509804f, 0.27058825f, 1f));
        styleBox3.Set("corner_radius_top_left", 4);
        styleBox3.Set("corner_radius_top_right", 4);
        styleBox3.Set("corner_radius_bottom_right", 4);
        styleBox3.Set("corner_radius_bottom_left", 4);
        styleBox3.Set("expand_margin_left", -2.0);
        styleBox3.Set("expand_margin_top", -2.0);
        styleBox3.Set("expand_margin_right", -2.0);
        styleBox3.Set("expand_margin_bottom", -2.0);
        styleBox3.Set("shadow_color", new Color(0f, 0f, 0f, 0.5f));
        styleBox3.Set("shadow_size", 2);
        theme.SetStylebox("completion", "CodeEdit", styleBox3);

        var styleBox4 = new StyleBoxFlat();
        styleBox4.ResourceSceneUniqueId = "StyleBoxFlat_82udi";
        styleBox4.Set("content_margin_left", 4.0);
        styleBox4.Set("content_margin_top", 4.0);
        styleBox4.Set("content_margin_right", 4.0);
        styleBox4.Set("content_margin_bottom", 4.0);
        styleBox4.Set("bg_color", new Color(0.117647f, 0.117647f, 0.117647f, 1f));
        styleBox4.Set("draw_center", false);
        styleBox4.Set("border_color", new Color(0.16470589f, 0.16862746f, 0.17254902f, 1f));
        styleBox4.Set("corner_radius_top_left", 8);
        styleBox4.Set("corner_radius_top_right", 8);
        styleBox4.Set("corner_radius_bottom_right", 8);
        styleBox4.Set("corner_radius_bottom_left", 8);
        styleBox4.Set("corner_detail", 5);
        theme.SetStylebox("normal", "CodeEdit", styleBox4);
        theme.SetStylebox("read_only", "CodeEdit", styleBox4);

        var styleBox5 = new StyleBoxFlat();
        styleBox5.ResourceSceneUniqueId = "StyleBoxFlat_21uq4";
        styleBox5.Set("content_margin_left", 1.0);
        styleBox5.Set("content_margin_top", 0.0);
        styleBox5.Set("content_margin_right", 1.0);
        styleBox5.Set("content_margin_bottom", 1.0);
        styleBox5.Set("draw_center", false);
        styleBox5.Set("border_color", new Color(0.16470589f, 0.16862746f, 0.17254902f, 1f));
        theme.SetStylebox("panel", "CodeEditorTabContainer", styleBox5);

        var styleBox6 = new StyleBoxFlat();
        styleBox6.ResourceSceneUniqueId = "StyleBoxFlat_an00s";
        styleBox6.Set("content_margin_left", 10.0);
        styleBox6.Set("content_margin_top", 4.0);
        styleBox6.Set("content_margin_right", 10.0);
        styleBox6.Set("content_margin_bottom", 4.0);
        styleBox6.Set("bg_color", new Color(1f, 1f, 1f, 0.1254902f));
        styleBox6.Set("border_color", new Color(1f, 1f, 1f, 0.75f));
        styleBox6.Set("corner_radius_top_left", 6);
        styleBox6.Set("corner_radius_top_right", 6);
        styleBox6.Set("corner_radius_bottom_right", 6);
        styleBox6.Set("corner_radius_bottom_left", 6);
        styleBox6.Set("corner_detail", 5);
        theme.SetStylebox("tab_hovered", "CodeEditorTabContainer", styleBox6);

        var styleBox7 = new StyleBoxFlat();
        styleBox7.ResourceSceneUniqueId = "StyleBoxFlat_ua1vr";
        styleBox7.Set("content_margin_left", 10.0);
        styleBox7.Set("content_margin_top", 4.0);
        styleBox7.Set("content_margin_right", 10.0);
        styleBox7.Set("content_margin_bottom", 4.0);
        styleBox7.Set("bg_color", new Color(1f, 1f, 1f, 0.1254902f));
        styleBox7.Set("border_color", new Color(1f, 1f, 1f, 0.75f));
        styleBox7.Set("corner_radius_top_left", 6);
        styleBox7.Set("corner_radius_top_right", 6);
        styleBox7.Set("corner_radius_bottom_right", 6);
        styleBox7.Set("corner_radius_bottom_left", 6);
        styleBox7.Set("corner_detail", 5);
        theme.SetStylebox("tab_selected", "CodeEditorTabContainer", styleBox7);

        var styleBox8 = new StyleBoxFlat();
        styleBox8.ResourceSceneUniqueId = "StyleBoxFlat_ml8q5";
        styleBox8.Set("content_margin_left", 10.0);
        styleBox8.Set("content_margin_top", 4.0);
        styleBox8.Set("content_margin_right", 10.0);
        styleBox8.Set("content_margin_bottom", 4.0);
        styleBox8.Set("bg_color", new Color(0f, 0f, 0f, 0f));
        styleBox8.Set("draw_center", false);
        styleBox8.Set("corner_radius_top_left", 6);
        styleBox8.Set("corner_radius_top_right", 6);
        styleBox8.Set("corner_radius_bottom_right", 6);
        styleBox8.Set("corner_radius_bottom_left", 6);
        styleBox8.Set("corner_detail", 5);
        theme.SetStylebox("tab_unselected", "CodeEditorTabContainer", styleBox8);

        var styleBox9 = new StyleBoxFlat();
        styleBox9.ResourceSceneUniqueId = "StyleBoxFlat_5oigc";
        styleBox9.Set("content_margin_left", 4.0);
        styleBox9.Set("content_margin_top", 4.0);
        styleBox9.Set("content_margin_right", 4.0);
        styleBox9.Set("content_margin_bottom", 4.0);
        styleBox9.Set("bg_color", new Color(0f, 0f, 0f, 0f));
        styleBox9.Set("draw_center", false);
        theme.SetStylebox("tabbar_background", "CodeEditorTabContainer", styleBox9);

        var styleBox10 = new StyleBoxFlat();
        styleBox10.ResourceSceneUniqueId = "StyleBoxFlat_dvhtt";
        styleBox10.Set("content_margin_left", 12.0);
        styleBox10.Set("content_margin_top", 10.0);
        styleBox10.Set("content_margin_right", 12.0);
        styleBox10.Set("content_margin_bottom", 10.0);
        styleBox10.Set("bg_color", new Color(0.16862746f, 0.1764706f, 0.1882353f, 1f));
        styleBox10.Set("border_width_left", 1);
        styleBox10.Set("border_width_top", 1);
        styleBox10.Set("border_width_right", 1);
        styleBox10.Set("border_width_bottom", 1);
        styleBox10.Set("border_color", new Color(0.24313726f, 0.2509804f, 0.27058825f, 1f));
        styleBox10.Set("corner_radius_top_left", 4);
        styleBox10.Set("corner_radius_top_right", 4);
        styleBox10.Set("corner_radius_bottom_right", 4);
        styleBox10.Set("corner_radius_bottom_left", 4);
        styleBox10.Set("expand_margin_left", -2.0);
        styleBox10.Set("expand_margin_top", -2.0);
        styleBox10.Set("expand_margin_right", -2.0);
        styleBox10.Set("expand_margin_bottom", -2.0);
        styleBox10.Set("shadow_color", new Color(0f, 0f, 0f, 0.5019608f));
        styleBox10.Set("shadow_size", 2);
        theme.SetStylebox("panel", "EditorHoverPopupPanelContainer", styleBox10);

        var styleBox11 = new StyleBoxFlat();
        styleBox11.ResourceSceneUniqueId = "StyleBoxFlat_hrgw7";
        styleBox11.Set("content_margin_left", 4.0);
        styleBox11.Set("content_margin_top", 4.0);
        styleBox11.Set("content_margin_right", 4.0);
        styleBox11.Set("content_margin_bottom", 4.0);
        styleBox11.Set("bg_color", new Color(0.1f, 0.1f, 0.1f, 0.6f));
        styleBox11.Set("corner_radius_top_left", 3);
        styleBox11.Set("corner_radius_top_right", 3);
        styleBox11.Set("corner_radius_bottom_right", 3);
        styleBox11.Set("corner_radius_bottom_left", 3);
        styleBox11.Set("corner_detail", 5);
        theme.SetStylebox("title_collapsed_panel", "FoldableContainer", styleBox11);

        var styleBox12 = new StyleBoxFlat();
        styleBox12.ResourceSceneUniqueId = "StyleBoxFlat_njudc";
        styleBox12.Set("content_margin_left", 4.0);
        styleBox12.Set("content_margin_top", 4.0);
        styleBox12.Set("content_margin_right", 4.0);
        styleBox12.Set("content_margin_bottom", 4.0);
        styleBox12.Set("bg_color", new Color(0.15540645f, 0.15904477f, 0.16268319f, 1f));
        styleBox12.Set("corner_radius_top_left", 6);
        styleBox12.Set("corner_radius_top_right", 6);
        styleBox12.Set("corner_radius_bottom_right", 6);
        styleBox12.Set("corner_radius_bottom_left", 6);
        styleBox12.Set("corner_detail", 5);
        theme.SetStylebox("hover", "IdeSidebarButton", styleBox12);

        var styleBox13 = new StyleBoxFlat();
        styleBox13.ResourceSceneUniqueId = "StyleBoxFlat_dsk6k";
        styleBox13.Set("content_margin_left", 4.0);
        styleBox13.Set("content_margin_top", 4.0);
        styleBox13.Set("content_margin_right", 4.0);
        styleBox13.Set("content_margin_bottom", 4.0);
        styleBox13.Set("bg_color", new Color(0.1f, 0.1f, 0.1f, 0.6f));
        styleBox13.Set("draw_center", false);
        styleBox13.Set("corner_radius_top_left", 6);
        styleBox13.Set("corner_radius_top_right", 6);
        styleBox13.Set("corner_radius_bottom_right", 6);
        styleBox13.Set("corner_radius_bottom_left", 6);
        styleBox13.Set("corner_detail", 5);
        theme.SetStylebox("normal", "IdeSidebarButton", styleBox13);
        theme.SetStylebox("pressed", "IdeSidebarButton", styleBox12);

        var styleBox14 = new StyleBoxFlat();
        styleBox14.ResourceSceneUniqueId = "StyleBoxFlat_4dj27";
        styleBox14.Set("content_margin_left", 4.0);
        styleBox14.Set("content_margin_top", 4.0);
        styleBox14.Set("content_margin_right", 4.0);
        styleBox14.Set("content_margin_bottom", 4.0);
        styleBox14.Set("bg_color", new Color(1f, 1f, 1f, 0.03137255f));
        styleBox14.Set("border_width_left", 1);
        styleBox14.Set("border_width_top", 1);
        styleBox14.Set("border_width_right", 1);
        styleBox14.Set("border_width_bottom", 1);
        styleBox14.Set("border_color", new Color(1f, 1f, 1f, 0.101960786f));
        styleBox14.Set("border_blend", true);
        styleBox14.Set("corner_radius_top_left", 3);
        styleBox14.Set("corner_radius_top_right", 3);
        styleBox14.Set("corner_radius_bottom_right", 3);
        styleBox14.Set("corner_radius_bottom_left", 3);
        styleBox14.Set("corner_detail", 5);
        theme.SetStylebox("normal", "LineEdit", styleBox14);

        var styleBox15 = new StyleBoxFlat();
        styleBox15.ResourceSceneUniqueId = "StyleBoxFlat_ch0dy";
        styleBox15.Set("content_margin_left", 4.0);
        styleBox15.Set("content_margin_top", 4.0);
        styleBox15.Set("content_margin_right", 4.0);
        styleBox15.Set("content_margin_bottom", 4.0);
        styleBox15.Set("bg_color", new Color(0.5609549f, 0.5609549f, 0.56095487f, 0.6f));
        styleBox15.Set("draw_center", false);
        styleBox15.Set("corner_radius_top_left", 3);
        styleBox15.Set("corner_radius_top_right", 3);
        styleBox15.Set("corner_radius_bottom_right", 3);
        styleBox15.Set("corner_radius_bottom_left", 3);
        styleBox15.Set("corner_detail", 5);
        theme.SetStylebox("disabled", "NavigationArrowButton", styleBox15);

        var styleBox16 = new StyleBoxFlat();
        styleBox16.ResourceSceneUniqueId = "StyleBoxFlat_al7qp";
        styleBox16.Set("content_margin_left", 4.0);
        styleBox16.Set("content_margin_top", 4.0);
        styleBox16.Set("content_margin_right", 4.0);
        styleBox16.Set("content_margin_bottom", 4.0);
        styleBox16.Set("bg_color", new Color(0.28235295f, 0.28235295f, 0.28235295f, 0.6f));
        styleBox16.Set("corner_radius_top_left", 3);
        styleBox16.Set("corner_radius_top_right", 3);
        styleBox16.Set("corner_radius_bottom_right", 3);
        styleBox16.Set("corner_radius_bottom_left", 3);
        styleBox16.Set("corner_detail", 5);
        theme.SetStylebox("hover", "NavigationArrowButton", styleBox16);
        theme.SetStylebox("normal", "NavigationArrowButton", styleBox15);

        var styleBox17 = new StyleBoxFlat();
        styleBox17.ResourceSceneUniqueId = "StyleBoxFlat_qn0n3";
        styleBox17.Set("content_margin_left", 4.0);
        styleBox17.Set("content_margin_top", 4.0);
        styleBox17.Set("content_margin_right", 4.0);
        styleBox17.Set("content_margin_bottom", 4.0);
        styleBox17.Set("bg_color", new Color(0.09411765f, 0.09411765f, 0.09411765f, 0.6f));
        styleBox17.Set("corner_radius_top_left", 3);
        styleBox17.Set("corner_radius_top_right", 3);
        styleBox17.Set("corner_radius_bottom_right", 3);
        styleBox17.Set("corner_radius_bottom_left", 3);
        styleBox17.Set("corner_detail", 5);
        theme.SetStylebox("pressed", "NavigationArrowButton", styleBox17);

        var styleBox18 = new StyleBoxFlat();
        styleBox18.ResourceSceneUniqueId = "StyleBoxFlat_6t7l7";
        styleBox18.Set("bg_color", new Color(1f, 1f, 1f, 0.030000001f));
        styleBox18.Set("border_width_left", 1);
        styleBox18.Set("border_width_top", 1);
        styleBox18.Set("border_width_right", 1);
        styleBox18.Set("border_width_bottom", 1);
        styleBox18.Set("border_color", new Color(1f, 1f, 1f, 0.101960786f));
        theme.SetStylebox("panel", "Panel", styleBox18);

        var styleBox19 = new StyleBoxFlat();
        styleBox19.ResourceSceneUniqueId = "StyleBoxFlat_6e8is";
        styleBox19.Set("content_margin_left", 0.0);
        styleBox19.Set("content_margin_top", 0.0);
        styleBox19.Set("content_margin_right", 0.0);
        styleBox19.Set("content_margin_bottom", 0.0);
        styleBox19.Set("bg_color", new Color(1f, 1f, 1f, 0.030000001f));
        styleBox19.Set("border_width_left", 1);
        styleBox19.Set("border_width_top", 1);
        styleBox19.Set("border_width_right", 1);
        styleBox19.Set("border_width_bottom", 1);
        styleBox19.Set("border_color", new Color(1f, 1f, 1f, 0.101960786f));
        styleBox19.Set("corner_radius_top_left", 8);
        styleBox19.Set("corner_radius_top_right", 8);
        styleBox19.Set("corner_radius_bottom_right", 8);
        styleBox19.Set("corner_radius_bottom_left", 8);
        theme.SetStylebox("panel", "PanelContainer", styleBox19);

        var styleBox20 = new StyleBoxFlat();
        styleBox20.ResourceSceneUniqueId = "StyleBoxFlat_amw38";
        styleBox20.Set("bg_color", new Color(0.1764706f, 0.1764706f, 0.1764706f, 1f));
        styleBox20.Set("corner_radius_top_left", 5);
        styleBox20.Set("corner_radius_top_right", 5);
        styleBox20.Set("corner_radius_bottom_right", 5);
        styleBox20.Set("corner_radius_bottom_left", 5);
        styleBox20.Set("shadow_color", new Color(0f, 0f, 0f, 0.11764706f));
        styleBox20.Set("shadow_size", 4);
        theme.SetStylebox("panel", "PopupPanel", styleBox20);
        theme.SetStylebox("tab_hovered", "TabBar", styleBox6);
        theme.SetStylebox("tab_selected", "TabBar", styleBox7);
        theme.SetStylebox("tab_unselected", "TabBar", styleBox8);

        var styleBox21 = new StyleBoxFlat();
        styleBox21.ResourceSceneUniqueId = "StyleBoxFlat_bk23l";
        styleBox21.Set("content_margin_left", 4.0);
        styleBox21.Set("content_margin_top", 4.0);
        styleBox21.Set("content_margin_right", 4.0);
        styleBox21.Set("content_margin_bottom", 4.0);
        styleBox21.Set("bg_color", new Color(1f, 1f, 1f, 0.75f));
        styleBox21.Set("draw_center", false);
        styleBox21.Set("corner_radius_top_left", 3);
        styleBox21.Set("corner_radius_top_right", 3);
        styleBox21.Set("corner_radius_bottom_right", 3);
        styleBox21.Set("corner_radius_bottom_left", 3);
        styleBox21.Set("corner_detail", 5);
        styleBox21.Set("expand_margin_left", 2.0);
        styleBox21.Set("expand_margin_top", 2.0);
        styleBox21.Set("expand_margin_right", 2.0);
        styleBox21.Set("expand_margin_bottom", 2.0);
        theme.SetStylebox("focus", "Terminal", styleBox21);

        var styleBox22 = new StyleBoxFlat();
        styleBox22.ResourceSceneUniqueId = "StyleBoxFlat_5srvn";
        styleBox22.Set("content_margin_left", 4.0);
        styleBox22.Set("content_margin_top", 4.0);
        styleBox22.Set("content_margin_right", 4.0);
        styleBox22.Set("content_margin_bottom", 4.0);
        styleBox22.Set("bg_color", new Color(0.1f, 0.1f, 0.1f, 0.6f));
        styleBox22.Set("draw_center", false);
        styleBox22.Set("border_color", new Color(0f, 0f, 0f, 0.6f));
        styleBox22.Set("corner_radius_top_left", 3);
        styleBox22.Set("corner_radius_top_right", 3);
        styleBox22.Set("corner_radius_bottom_right", 3);
        styleBox22.Set("corner_radius_bottom_left", 3);
        styleBox22.Set("corner_detail", 5);
        theme.SetStylebox("normal", "Terminal", styleBox22);

        var styleBox23 = new StyleBoxFlat();
        styleBox23.ResourceSceneUniqueId = "StyleBoxFlat_yqdk6";
        styleBox23.Set("content_margin_left", 4.0);
        styleBox23.Set("content_margin_top", 4.0);
        styleBox23.Set("content_margin_right", 4.0);
        styleBox23.Set("content_margin_bottom", 4.0);
        styleBox23.Set("bg_color", new Color(1f, 1f, 1f, 0.72156864f));
        styleBox23.Set("draw_center", false);
        styleBox23.Set("border_width_left", 1);
        styleBox23.Set("border_width_top", 1);
        styleBox23.Set("border_width_right", 1);
        styleBox23.Set("border_width_bottom", 1);
        styleBox23.Set("border_color", new Color(1f, 1f, 1f, 0.5686275f));
        styleBox23.Set("corner_radius_top_left", 3);
        styleBox23.Set("corner_radius_top_right", 3);
        styleBox23.Set("corner_radius_bottom_right", 3);
        styleBox23.Set("corner_radius_bottom_left", 3);
        styleBox23.Set("corner_detail", 5);
        styleBox23.Set("expand_margin_left", 1.0);
        styleBox23.Set("expand_margin_top", 1.0);
        styleBox23.Set("expand_margin_right", 1.0);
        styleBox23.Set("expand_margin_bottom", 1.0);
        theme.SetStylebox("cursor", "Tree", styleBox23);
        theme.SetStylebox("cursor_unfocused", "Tree", styleBox23);

        var styleBox24 = new StyleBoxFlat();
        styleBox24.ResourceSceneUniqueId = "StyleBoxFlat_un4ka";
        styleBox24.Set("content_margin_left", 4.0);
        styleBox24.Set("content_margin_top", 4.0);
        styleBox24.Set("content_margin_right", 4.0);
        styleBox24.Set("content_margin_bottom", 4.0);
        styleBox24.Set("bg_color", new Color(1f, 1f, 1f, 0.1254902f));
        styleBox24.Set("corner_radius_top_left", 10);
        styleBox24.Set("corner_radius_top_right", 10);
        styleBox24.Set("corner_radius_bottom_right", 10);
        styleBox24.Set("corner_radius_bottom_left", 10);
        styleBox24.Set("corner_detail", 6);
        theme.SetStylebox("grabber", "VScrollBar", styleBox24);

        var styleBox25 = new StyleBoxFlat();
        styleBox25.ResourceSceneUniqueId = "StyleBoxFlat_vru7m";
        styleBox25.Set("content_margin_left", 4.0);
        styleBox25.Set("content_margin_top", 4.0);
        styleBox25.Set("content_margin_right", 4.0);
        styleBox25.Set("content_margin_bottom", 4.0);
        styleBox25.Set("bg_color", new Color(1f, 1f, 1f, 0.2509804f));
        styleBox25.Set("corner_radius_top_left", 10);
        styleBox25.Set("corner_radius_top_right", 10);
        styleBox25.Set("corner_radius_bottom_right", 10);
        styleBox25.Set("corner_radius_bottom_left", 10);
        styleBox25.Set("corner_detail", 6);
        theme.SetStylebox("grabber_highlight", "VScrollBar", styleBox25);

        var styleBox26 = new StyleBoxFlat();
        styleBox26.ResourceSceneUniqueId = "StyleBoxFlat_2wjv5";
        styleBox26.Set("content_margin_left", 4.0);
        styleBox26.Set("content_margin_top", 4.0);
        styleBox26.Set("content_margin_right", 4.0);
        styleBox26.Set("content_margin_bottom", 4.0);
        styleBox26.Set("bg_color", new Color(1f, 1f, 1f, 0.1882353f));
        styleBox26.Set("corner_radius_top_left", 10);
        styleBox26.Set("corner_radius_top_right", 10);
        styleBox26.Set("corner_radius_bottom_right", 10);
        styleBox26.Set("corner_radius_bottom_left", 10);
        styleBox26.Set("corner_detail", 6);
        theme.SetStylebox("grabber_pressed", "VScrollBar", styleBox26);

        var styleBox27 = new StyleBoxFlat();
        styleBox27.ResourceSceneUniqueId = "StyleBoxFlat_enfp6";
        styleBox27.Set("content_margin_left", 10.0);
        styleBox27.Set("content_margin_top", 28.0);
        styleBox27.Set("content_margin_right", 10.0);
        styleBox27.Set("content_margin_bottom", 8.0);
        styleBox27.Set("bg_color", new Color(0.14767182f, 0.14767182f, 0.14767176f, 1f));
        styleBox27.Set("corner_radius_top_left", 3);
        styleBox27.Set("corner_radius_top_right", 3);
        styleBox27.Set("corner_radius_bottom_right", 3);
        styleBox27.Set("corner_radius_bottom_left", 3);
        styleBox27.Set("corner_detail", 5);
        styleBox27.Set("expand_margin_left", 8.0);
        styleBox27.Set("expand_margin_top", 32.0);
        styleBox27.Set("expand_margin_right", 8.0);
        styleBox27.Set("expand_margin_bottom", 6.0);
        theme.SetStylebox("embedded_border", "Window", styleBox27);

        var styleBox28 = new StyleBoxFlat();
        styleBox28.ResourceSceneUniqueId = "StyleBoxFlat_kta15";
        styleBox28.Set("content_margin_left", 10.0);
        styleBox28.Set("content_margin_top", 28.0);
        styleBox28.Set("content_margin_right", 10.0);
        styleBox28.Set("content_margin_bottom", 8.0);
        styleBox28.Set("bg_color", new Color(0.10747979f, 0.107479714f, 0.10747973f, 1f));
        styleBox28.Set("corner_radius_top_left", 3);
        styleBox28.Set("corner_radius_top_right", 3);
        styleBox28.Set("corner_radius_bottom_right", 3);
        styleBox28.Set("corner_radius_bottom_left", 3);
        styleBox28.Set("corner_detail", 5);
        styleBox28.Set("expand_margin_left", 8.0);
        styleBox28.Set("expand_margin_top", 32.0);
        styleBox28.Set("expand_margin_right", 8.0);
        styleBox28.Set("expand_margin_bottom", 6.0);
        theme.SetStylebox("embedded_unfocused_border", "Window", styleBox28);
        theme.SetColor("completion_background_color", "CodeEdit", new Color(1f, 1f, 1f, 0f));
        theme.SetColor("completion_selected_color", "CodeEdit", new Color(0.18039216f, 0.2627451f, 0.43137255f, 1f));
        theme.SetColor("current_line_color", "CodeEdit", new Color(0.05882353f, 0.05882353f, 0.05882353f, 1f));
        theme.SetColor("font_readonly_color", "CodeEdit", new Color(1f, 1f, 1f, 1f));
        theme.SetColor("search_result_border_color", "CodeEdit", new Color(0.14117648f, 0.35686275f, 0.50980395f, 1f));
        theme.SetColor("search_result_color", "CodeEdit", new Color(0.3f, 0.3f, 0.3f, 0.4117647f));
        theme.SetColor("selection_color", "CodeEdit", new Color(0.14117648f, 0.35686275f, 0.50980395f, 1f));
        theme.SetFont("font", "CodeEdit", ResourceLoader.Load<Font>("uid://cctwlwcoycek7"));
        theme.SetFontSize("font_size", "CodeEdit", 18);
        theme.SetColor("font_color", "Control", new Color(0.98039216f, 1f, 1f, 0.77254903f));
        theme.SetColor("collapsed_font_color", "FoldableContainer", new Color(0.83137256f, 0.83137256f, 0.83137256f, 1f));
        theme.SetColor("font_color", "FoldableContainer", new Color(0.83137256f, 0.83137256f, 0.83137256f, 1f));
        theme.SetColor("font_color", "Gray500Label", new Color(0.5137255f, 0.5137255f, 0.5137255f, 1f));
        theme.SetColor("font_color", "Gray600Label", new Color(0.67058825f, 0.67058825f, 0.67058825f, 1f));
        theme.SetColor("font_color", "Gray700Label", new Color(0.83137256f, 0.83137256f, 0.83137256f, 1f));
        theme.SetColor("font_color", "Gray800Label", new Color(0.9137255f, 0.9137255f, 0.9137255f, 1f));
        theme.SetColor("font_color", "IdeSidebarButton", new Color(0.54901963f, 0.54901963f, 0.54901963f, 1f));
        theme.SetColor("font_focus_color", "IdeSidebarButton", new Color(0.7490196f, 0.7490196f, 0.7490196f, 1f));
        theme.SetColor("font_hover_color", "IdeSidebarButton", new Color(0.54901963f, 0.54901963f, 0.54901963f, 1f));
        theme.SetColor("font_hover_pressed_color", "IdeSidebarButton", new Color(0.7490196f, 0.7490196f, 0.7490196f, 1f));
        theme.SetColor("font_pressed_color", "IdeSidebarButton", new Color(0.7490196f, 0.7490196f, 0.7490196f, 1f));
        theme.SetColor("icon_hover_color", "IdeSidebarButton", new Color(0.54901963f, 0.54901963f, 0.54901963f, 1f));
        theme.SetColor("icon_hover_pressed_color", "IdeSidebarButton", new Color(0.7490196f, 0.7490196f, 0.7490196f, 1f));
        theme.SetColor("icon_normal_color", "IdeSidebarButton", new Color(0.54901963f, 0.54901963f, 0.54901963f, 1f));
        theme.SetColor("icon_pressed_color", "IdeSidebarButton", new Color(0.7490196f, 0.7490196f, 0.7490196f, 1f));
        theme.SetColor("icon_disabled_color", "NavigationArrowButton", new Color(0.45064795f, 0.45064837f, 0.45064825f, 1f));
        theme.SetColor("icon_hover_color", "NavigationArrowButton", new Color(0.74509805f, 0.74509805f, 0.74509805f, 1f));
        theme.SetColor("icon_hover_pressed_color", "NavigationArrowButton", new Color(0.74509805f, 0.74509805f, 0.74509805f, 1f));
        theme.SetColor("icon_normal_color", "NavigationArrowButton", new Color(0.74509805f, 0.74509805f, 0.74509805f, 1f));
        theme.SetColor("icon_pressed_color", "NavigationArrowButton", new Color(0.74509805f, 0.74509805f, 0.74509805f, 1f));
        theme.SetIcon("close", "TabBar", ResourceLoader.Load<Texture2D>("uid://d0wy2vggrfgdh"));
        theme.SetColor("ansi_0_color", "Terminal", new Color(0f, 0f, 0f, 1f));
        theme.SetColor("ansi_10_color", "Terminal", new Color(0f, 1f, 0f, 1f));
        theme.SetColor("ansi_11_color", "Terminal", new Color(1f, 1f, 0f, 1f));
        theme.SetColor("ansi_12_color", "Terminal", new Color(0.360784f, 0.360784f, 1f, 1f));
        theme.SetColor("ansi_13_color", "Terminal", new Color(1f, 0f, 1f, 1f));
        theme.SetColor("ansi_14_color", "Terminal", new Color(0f, 1f, 1f, 1f));
        theme.SetColor("ansi_15_color", "Terminal", new Color(1f, 1f, 1f, 1f));
        theme.SetColor("ansi_1_color", "Terminal", new Color(0.803922f, 0f, 0f, 1f));
        theme.SetColor("ansi_2_color", "Terminal", new Color(0f, 0.803922f, 0f, 1f));
        theme.SetColor("ansi_3_color", "Terminal", new Color(0.803922f, 0.803922f, 0f, 1f));
        theme.SetColor("ansi_4_color", "Terminal", new Color(0f, 0f, 0.933333f, 1f));
        theme.SetColor("ansi_5_color", "Terminal", new Color(0.803922f, 0f, 0.803922f, 1f));
        theme.SetColor("ansi_6_color", "Terminal", new Color(0f, 0.803922f, 0.803922f, 1f));
        theme.SetColor("ansi_7_color", "Terminal", new Color(0.898039f, 0.898039f, 0.898039f, 1f));
        theme.SetColor("ansi_8_color", "Terminal", new Color(0.498039f, 0.498039f, 0.498039f, 1f));
        theme.SetColor("ansi_9_color", "Terminal", new Color(1f, 0f, 0f, 1f));
        theme.SetColor("background_color", "Terminal", new Color(0f, 0f, 0f, 0f));
        theme.SetColor("foreground_color", "Terminal", new Color(0.875f, 0.875f, 0.875f, 1f));
        theme.SetFont("bold_font", "Terminal", ResourceLoader.Load<Font>("uid://vmgmcu8gc6nt"));
        theme.SetFont("bold_italics_font", "Terminal", ResourceLoader.Load<Font>("uid://vmgmcu8gc6nt"));
        theme.SetFont("italics_font", "Terminal", ResourceLoader.Load<Font>("uid://vmgmcu8gc6nt"));
        theme.SetFont("normal_font", "Terminal", ResourceLoader.Load<Font>("uid://vmgmcu8gc6nt"));
        theme.SetFontSize("font_size", "Terminal", 16);
        theme.SetConstant("IsLight1OrDark2", "ThemeInfo", 2);

        return theme;
    }
}
